# This workflow calls a reusable main workflow that handles actual deployment

# info
name: 'Deploy Stellaris mod update'
run-name: "${{ github.actor }} triggered a ${{ inputs.versionType }} update for ${{ github.event.repository.name }}"

on:
  # for calling manually and getting input popups
  workflow_dispatch:
    inputs:
      versionType:
        description: 'Version type to bump, follows semantic versioning'
        required: true
        default: 'Patch'
        type: choice
        options:
        - 'Major'
        - 'Minor'
        - 'Patch'
      versionStellaris:
        description: 'Stellaris version to support'
        required: true
        type: string
      useChangelog:
        description: |
          Fill in changelog for release?

          Expects a CHANGELOG.md file in target repo
        required: true
        type: boolean
      
permissions:
  contents: write

jobs:
  use_updateStellarisMod_workflow:
    uses: aerolfos/stellaris_mod_deploy_action/.github/workflows/updateStellarisMod.yml@main
    with: 
      versionType: ${{ inputs.versionType }}
      versionStellaris: ${{ inputs.versionStellaris }}
      useChangelog: ${{ inputs.useChangelog }}

